version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-network
  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongo-network
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: password
      MONGO_DATABASE: my-db
      MONGO_SERVER: mongodb
    networks:
      - mongo-network
networks:
  mongo-network:
    driver: bridge
