version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: overlord
      MONGO_INITDB_ROOT_PASSWORD: +lhK>5Ge-MI9gwLR
    networks:
      - mongo-network
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: overlord
      ME_CONFIG_MONGODB_ADMINPASSWORD: +lhK>5Ge-MI9gwLR
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongo-network
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_USER: overlord
      MONGO_PASSWORD: +lhK>5Ge-MI9gwLR
      MONGO_DATABASE: my-db
      MONGO_SERVER: mongodb
    networks:
      - mongo-network
networks:
  mongo-network:
    driver: bridge
